### PR TITLE
Adding Jenkins Org 2019 Proposals

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
* Create A Folder with name <Organization-name> if your organization is not listed
* Create .md file with name <year-proposals.md> if there is no file for your organization see [here](CiviCRM/2019-proposals.md)
* Add your  GSoC Project Title
* Add accepted GSoC Proposal link with the format `[link](<proposal link>)`
* Add GSoC Project link with the format `[link](<project link>)`

NB: 
* Please ensure that shared links are publickly accesible
* Please remove personal information from your proposals if you don't want to share them

### CODE REVIEW

**Comment by prondubuisi** [comment]
Thanks for bringing Jenkins to us @markyjackson-taulia . Bringing into markup base. lol

**Comment by oleg-nenashev** [comment]
I believe there is a mismatch here. The Repository is about project proposals, but this list references the actual project pages from accepted projects. The most of the project pages link the original proposals, but it might be difficult for students to find them.

Also, Would be nice to get Jenkins in README once it is cleaned up

**Comment by prondubuisi** [comment]
Hello @oleg-nenashev turns out I did not click through to confirm we had direct links to the proposal. Thanks for pointing this out. I will fix and add Jenkins to readme. Lesson learnt. Never merge without testing cc @markyjackson-taulia

**Comment by markyjackson-taulia** [comment]
I will fix in the am

**Comment by prondubuisi** [comment]
> I will fix in the am

Cool. Thanks @markyjackson-taulia

**Comment by prondubuisi** [comment]
Hello @markyjackson-taulia I am guessing you are busy with other things. So I will be fixing this issue.

**Comment by markyjackson-taulia** [comment]
My goal was to get to this today but the day got away. I can try later in the week but if you get to it first thank you

**Comment by prondubuisi** [comment]
Hello @markyjackson-taulia @oleg-nenashev, I have added Jenkins project to the Readme.md, as well as updated the proposal links. This two projects have no proposal links on the Jenkins website though  https://jenkins.io/projects/gsoc/2019/remoting-over-apache-kafka-docker-k8s-features/, https://jenkins.io/projects/gsoc/2019/working-hours-improvements/, Would be very grateful to get links to the proposals so I can update them. Thanks.

**Comment by markyjackson-taulia** [comment]
> Hello @markyjackson-taulia @oleg-nenashev, I have added Jenkins project to the Readme.md, as well as updated the proposal links. This two projects have no proposal links on the Jenkins website though https://jenkins.io/projects/gsoc/2019/remoting-over-apache-kafka-docker-k8s-features/, https://jenkins.io/projects/gsoc/2019/working-hours-improvements/, Would be very grateful to get links to the proposals so I can update them. Thanks.

Corrected in pr #32

**Pull request merged**
